[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aab9b3825ef6955547eadb101cd6047c3d08ef61"
libc = "glibc"
os = "linux"

    [[xrt.download]]
    sha256 = "75e43d22afaa36cb131d81908fade9ffbfc2cdcfc807ce75cdb9665bd9e1b3b1"
    url = "https://github.com/JuliaBinaryWrappers/xrt_jll.jl/releases/download/xrt-v2.26.0+0/xrt.v2.26.0.x86_64-linux-gnu-cxx11.tar.gz"
[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47dd8649640281e3490d90345074d16d250d02f6"
os = "windows"

    [[xrt.download]]
    sha256 = "42a1d38d2c5fe180ee9b359dd5fb200b434b79c3a85b7453e436a96bf27fa5f2"
    url = "https://github.com/JuliaBinaryWrappers/xrt_jll.jl/releases/download/xrt-v2.26.0+0/xrt.v2.26.0.x86_64-w64-mingw32-cxx11.tar.gz"
