# Autogenerated wrapper script for xrt_jll for x86_64-w64-mingw32-cxx11
export libxdp_core, libxilinxopencl, libxrt_core, libxrt_coreutil, libxrtxx, xbutil, xclbinutil

using ocl_icd_jll
using rapidjson_jll
JLLWrappers.@generate_wrapper_header("xrt")
JLLWrappers.@declare_library_product(libxdp_core, "libxdp_core.dll")
JLLWrappers.@declare_library_product(libxilinxopencl, "libxilinxopencl.dll")
JLLWrappers.@declare_library_product(libxrt_core, "libxrt_core.dll")
JLLWrappers.@declare_library_product(libxrt_coreutil, "libxrt_coreutil.dll")
JLLWrappers.@declare_library_product(libxrtxx, "libxrt++.dll")
JLLWrappers.@declare_executable_product(xbutil)
JLLWrappers.@declare_executable_product(xclbinutil)
function __init__()
    JLLWrappers.@generate_init_header(ocl_icd_jll, rapidjson_jll)
    JLLWrappers.@init_library_product(
        libxdp_core,
        "bin\\libxdp_core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxilinxopencl,
        "bin\\libxilinxopencl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxrt_core,
        "bin\\libxrt_core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxrt_coreutil,
        "bin\\libxrt_coreutil.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxrtxx,
        "bin\\libxrt++.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        xbutil,
        "bin\\unwrapped\\xbutil.exe",
    )

    JLLWrappers.@init_executable_product(
        xclbinutil,
        "bin\\unwrapped\\xclbinutil.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
